config/routes.rb
Rails.application.routes.draw do
  resources :profile_cards
  root "profile_cards#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile_card.rb
class ProfileCard < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profile_cards_controller.rb
class ProfileCardsController < ApplicationController
  before_action :set_profile_card, only: %i[ show edit update destroy ]

  # GET /profile_cards or /profile_cards.json
  def index
    @profile_cards = ProfileCard.all
  end

  # GET /profile_cards/1 or /profile_cards/1.json
  def show
  end

  # GET /profile_cards/new
  def new
    @profile_card = ProfileCard.new
  end

  # GET /profile_cards/1/edit
  def edit
  end

  # POST /profile_cards or /profile_cards.json
  def create
    @profile_card = ProfileCard.new(profile_card_params)

    respond_to do |format|
      if @profile_card.save
        format.html { redirect_to profile_card_url(@profile_card), notice: "Profile card was successfully created." }
        format.json { render :show, status: :created, location: @profile_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profile_cards/1 or /profile_cards/1.json
  def update
    respond_to do |format|
      if @profile_card.update(profile_card_params)
        format.html { redirect_to profile_card_url(@profile_card), notice: "Profile card was successfully updated." }
        format.json { render :show, status: :ok, location: @profile_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_cards/1 or /profile_cards/1.json
  def destroy
    @profile_card.destroy

    respond_to do |format|
      format.html { redirect_to profile_cards_url, notice: "Profile card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile_card
      @profile_card = ProfileCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_card_params
      params.require(:profile_card).permit(:background, :picture, :first_name, :last_name, :birth_year, :hobbies)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_cards_helper.rb
module ProfileCardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfileCards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profile_cards/_form.html.erb
<%= form_with(model: profile_card) do |form| %>
  <% if profile_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile_card.errors.count, "error") %> prohibited this profile_card from being saved:</h2>

      <ul>
        <% profile_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Fond %>
    <br/>
    <%= form.text_area :background %>
  </div>

  <div class="field">
    <%= form.label :"Image de profil" %>
    <br/>
    <%= form.text_area :picture %>
  </div>

  <div class="field">
    <%= form.label :"Prénom" %>
    <br/>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :Nom %>
    <br/>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :"Année de naissance" %>
    <br/>
    <%= form.number_field :birth_year %>
  </div>

  <div class="field">
    <%= form.label :Activités %>
    <br/>
    <%= form.text_area :hobbies %>
  </div>

  <div class="btn">
    <%= form.submit "Valider"%>
  </div>
<% end %>

app/views/profile_cards/edit.html.erb
<h1>Editing Profile Card</h1>

<%= render 'form', profile_card: @profile_card %>


<div class="instructions">
  <%= link_to 'Afficher', @profile_card %> |
  <%= link_to 'Valider', profile_cards_path %>
</div>

app/views/profile_cards/index.html.erb
<header>
  <%# <div class="instructions"> %>
  <h1>Profile Cards</h1>
</header>

<div class="card-image">
  <%= image_tag 'https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F0e345515-0dbb-4ab7-afdf-897c154f282f%2FUntitled.png?table=block&id=1ce91531-991d-44f9-acd6-252153380380&spaceId=2b05fb9e-59eb-466c-a39b-26975048f356&width=1530&userId=aed7305d-bf21-47c3-a179-e9e251f13ace&cache=v2' %>
</div>

<main>


    <%= link_to 'Créer une carte'.html_safe, new_profile_card_path, class: "button"%>
    <%# <%= link_to 'New Profile Card', new_profile_card_path %>


    <table>

      <thead>
        <tr>
          <br/>
          <div class="view-other-cards">
            <p><strong>Voir les autres cartes de profil : <br/></strong></p>
            <th colspan="3"></th>
          </div>
        </tr>
      </thead>

      <tbody>
        <div class="other-cards">
          <p>Nom de la carte</p>
          <% @profile_cards.each do |profile_card| %>
            <tr>
              <td><%= profile_card.first_name %></td>
              <td><%= link_to 'Show', profile_card %></td>
              <td><%= link_to 'Edit', edit_profile_card_path(profile_card) %></td>
              <td><%= link_to 'Destroy', profile_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </div>
      </tbody>

    </table>

    <br>



</main>

app/views/profile_cards/new.html.erb
<h1>New Profile Card</h1>

<%= render 'form', profile_card: @profile_card %>


<div class="instructions">
  <%= link_to 'Annuler', profile_cards_path %>
</div>

app/views/profile_cards/show.html.erb
<%#< id="notice"><%= notice %> </>
<h1>View Card</h1>


<div class="empty-space">
</div>

<div class="card" style="background-image: url('<%= @profile_card.background %>')">
  <div class="final-show">
    <div class="background-card">
      <a>
        <%# <strong>Fond:</strong> %>
      </a>
    </div>
  </div>


  <div class="final-show">
    <div class="profile-picture-card">

        <%# <strong>Image de profil:</strong> %>
        <%= image_tag @profile_card.picture %>

    </div>
  </div>

  <div class="final-show">
    <p>
      <strong>Prénom:</strong>
      <%= @profile_card.first_name %>
    </p>
  </div>

  <div class="final-show">
    <p>
      <strong>Nom:</strong>
      <%= @profile_card.last_name %>
    </p>
  </div>

  <div class="final-show">
    <p>
      <strong>Année de naissance:</strong>
      <%= @profile_card.birth_year %>
    </p>
  </div>

  <div class="final-show">
    <p>
      <strong>Activités:</strong>
      <%= @profile_card.hobbies %>
    </p>
  </div>
</div>

<div class="instructions">
  <%= link_to 'Modifier', edit_profile_card_path(@profile_card) %> |
  <%= link_to 'Valider', profile_cards_path %>
</div>